// YOUR FIRST PROGRAM

// ANYTHING STARTING WITH A '#'IS CALLED A PREPROCESSOR DIRECTIVE.
// THIS TELLS THE COMPILER WHAT TO DO BEFORE COMPILATION,
// LIKE ADDING OTHER LIBRARIES, DEFINING MACROS (WE'LL GO THROUGH THAT LATER).
// 'include' DIRECTIVE TELLS THE COMPILER WHICH ALL LIBRARIES TO INCLUDE BEFORE EXECUTION
// WE INCLUDED THE LIBRARY 'iostream' TO ENABLE INPUT/OUTPUT FOR THE PROGRAM.
// 'IOSTREAM' MANAGES INPUT OUTPUT STREAMS.

#include <iostream>

// 'std' MANAGES STANDARD I/O METHODS HERE. MAKES cout & cin WORK.

using namespace std;

// main FUNCTION --> START OF EVERY PROGRAM, PROGRAM STARTS BY EXECUTING CODE FROM main FUNCTION

int main()
{
    // cout --> Used to output the file onto the terminal
    cout << "Hello World!\n";
    // EVERY PROGRAM ENDS WHEN THE MAIN FUNCTION RETURNS A VALUE, IN THIS CASE 0.
    // 0 IS TRADITIONALLY EXPECTED TO BE RETURNED BY THE PROGRAM IF THE PROGRAM
    // WORKED PROPERLY. YOU CAN RETURN ANY INTEGER VALUE HERE THOUGH.
    return 0;
}